// HolyOS — lokalizace e-mailů Compounder Portalu
// E-maily (pozvánka do Portalu + přihlašovací magic-link) se posílají v jazyce,
// který si zájemce zvolil na compounder.world (lead.lang). Když jazyk neznáme
// nebo není v překladech, použije se angličtina jako mezinárodní fallback.

// Každý záznam: inviteSubject/Preheader/Link a loginSubject/Preheader/Link jsou
// statické řetězce; inviteBody/loginBody jsou funkce (jméno) → text těla.
// V invite je jméno vždy vyplněné (povinné pole), v login může být prázdné.
const T = {
  en: {
    inviteSubject: 'Access to the Compounder Portal',
    invitePreheader: 'Your personal access to the economics, returns and parameters of the Compounder.',
    inviteBody: (n) => `Hello ${n},\n\nthank you for your interest in Compounding. This link gives you access to the Compounder Portal — economics, returns, technical parameters, connections, floor plans and the distribution model.\n\nThis link is personal, please do not share it.`,
    inviteLink: 'Open the Compounder Portal',
    loginSubject: 'Sign in to the Compounder Portal',
    loginPreheader: 'A link to sign in to the Compounder Portal (valid for 24 hours).',
    loginBody: (n) => `Hello${n ? ' ' + n : ''},\n\nuse this link to sign in to the Compounder Portal. The link is valid for 24 hours and is personal — please do not share it.\n\nIf you did not request this sign-in, you can safely ignore this email.`,
    loginLink: 'Sign in to the Portal',
  },
  cs: {
    inviteSubject: 'Vstup do Compounder Portalu',
    invitePreheader: 'Váš osobní přístup k ekonomice, návratnosti a parametrům Compounderu.',
    inviteBody: (n) => `Dobrý den, ${n},\n\nděkujeme za zájem o Compounding. Tímto odkazem se dostanete do Compounder Portalu — ekonomika, návratnost, technické parametry, přípojky, půdorysy a distribuční model.\n\nOdkaz je osobní, nesdílejte ho.`,
    inviteLink: 'Otevřít Compounder Portal',
    loginSubject: 'Přihlášení do Compounder Portalu',
    loginPreheader: 'Odkaz pro přihlášení do Compounder Portalu (platí 24 hodin).',
    loginBody: (n) => `Dobrý den${n ? ', ' + n : ''},\n\ntímto odkazem se přihlásíte do Compounder Portalu. Odkaz je platný 24 hodin a je osobní — nesdílejte ho.\n\nPokud jste o přihlášení nežádali, tento e-mail klidně ignorujte.`,
    loginLink: 'Přihlásit se do Portalu',
  },
  sk: {
    inviteSubject: 'Vstup do Compounder Portálu',
    invitePreheader: 'Váš osobný prístup k ekonomike, návratnosti a parametrom Compounderu.',
    inviteBody: (n) => `Dobrý deň, ${n},\n\nďakujeme za záujem o Compounding. Týmto odkazom sa dostanete do Compounder Portálu — ekonomika, návratnosť, technické parametre, prípojky, pôdorysy a distribučný model.\n\nOdkaz je osobný, nezdieľajte ho.`,
    inviteLink: 'Otvoriť Compounder Portál',
    loginSubject: 'Prihlásenie do Compounder Portálu',
    loginPreheader: 'Odkaz na prihlásenie do Compounder Portálu (platí 24 hodín).',
    loginBody: (n) => `Dobrý deň${n ? ', ' + n : ''},\n\ntýmto odkazom sa prihlásite do Compounder Portálu. Odkaz je platný 24 hodín a je osobný — nezdieľajte ho.\n\nAk ste o prihlásenie nežiadali, tento e-mail pokojne ignorujte.`,
    loginLink: 'Prihlásiť sa do Portálu',
  },
  de: {
    inviteSubject: 'Zugang zum Compounder Portal',
    invitePreheader: 'Ihr persönlicher Zugang zu Wirtschaftlichkeit, Rendite und Parametern des Compounders.',
    inviteBody: (n) => `Hallo ${n},\n\nvielen Dank für Ihr Interesse an Compounding. Mit diesem Link gelangen Sie ins Compounder Portal — Wirtschaftlichkeit, Rendite, technische Parameter, Anschlüsse, Grundrisse und das Vertriebsmodell.\n\nDer Link ist persönlich, bitte teilen Sie ihn nicht.`,
    inviteLink: 'Compounder Portal öffnen',
    loginSubject: 'Anmeldung im Compounder Portal',
    loginPreheader: 'Link zur Anmeldung im Compounder Portal (24 Stunden gültig).',
    loginBody: (n) => `Hallo${n ? ' ' + n : ''},\n\nmit diesem Link melden Sie sich im Compounder Portal an. Der Link ist 24 Stunden gültig und persönlich — bitte teilen Sie ihn nicht.\n\nFalls Sie diese Anmeldung nicht angefordert haben, können Sie diese E-Mail ignorieren.`,
    loginLink: 'Im Portal anmelden',
  },
  fr: {
    inviteSubject: 'Accès au Compounder Portal',
    invitePreheader: "Votre accès personnel à l'économie, au rendement et aux paramètres du Compounder.",
    inviteBody: (n) => `Bonjour ${n},\n\nmerci de votre intérêt pour le Compounding. Ce lien vous donne accès au Compounder Portal — économie, rendement, paramètres techniques, raccordements, plans et modèle de distribution.\n\nCe lien est personnel, merci de ne pas le partager.`,
    inviteLink: 'Ouvrir le Compounder Portal',
    loginSubject: 'Connexion au Compounder Portal',
    loginPreheader: 'Lien de connexion au Compounder Portal (valable 24 heures).',
    loginBody: (n) => `Bonjour${n ? ' ' + n : ''},\n\nce lien vous permet de vous connecter au Compounder Portal. Le lien est valable 24 heures et personnel — merci de ne pas le partager.\n\nSi vous n'avez pas demandé cette connexion, vous pouvez ignorer cet e-mail.`,
    loginLink: 'Se connecter au Portal',
  },
  es: {
    inviteSubject: 'Acceso al Compounder Portal',
    invitePreheader: 'Tu acceso personal a la economía, la rentabilidad y los parámetros del Compounder.',
    inviteBody: (n) => `Hola ${n},\n\ngracias por tu interés en el Compounding. Con este enlace accedes al Compounder Portal — economía, rentabilidad, parámetros técnicos, conexiones, planos y modelo de distribución.\n\nEl enlace es personal, no lo compartas.`,
    inviteLink: 'Abrir el Compounder Portal',
    loginSubject: 'Iniciar sesión en el Compounder Portal',
    loginPreheader: 'Enlace para iniciar sesión en el Compounder Portal (válido 24 horas).',
    loginBody: (n) => `Hola${n ? ' ' + n : ''},\n\ncon este enlace inicias sesión en el Compounder Portal. El enlace es válido 24 horas y es personal — no lo compartas.\n\nSi no has solicitado este inicio de sesión, puedes ignorar este correo.`,
    loginLink: 'Iniciar sesión en el Portal',
  },
  it: {
    inviteSubject: 'Accesso al Compounder Portal',
    invitePreheader: 'Il tuo accesso personale a economia, rendimento e parametri del Compounder.',
    inviteBody: (n) => `Buongiorno ${n},\n\ngrazie per il tuo interesse per il Compounding. Con questo link accedi al Compounder Portal — economia, rendimento, parametri tecnici, allacciamenti, planimetrie e modello di distribuzione.\n\nIl link è personale, non condividerlo.`,
    inviteLink: 'Apri il Compounder Portal',
    loginSubject: 'Accesso al Compounder Portal',
    loginPreheader: 'Link per accedere al Compounder Portal (valido 24 ore).',
    loginBody: (n) => `Buongiorno${n ? ' ' + n : ''},\n\ncon questo link accedi al Compounder Portal. Il link è valido 24 ore ed è personale — non condividerlo.\n\nSe non hai richiesto l'accesso, ignora pure questa email.`,
    loginLink: 'Accedi al Portal',
  },
  pt: {
    inviteSubject: 'Acesso ao Compounder Portal',
    invitePreheader: 'O seu acesso pessoal à economia, ao retorno e aos parâmetros do Compounder.',
    inviteBody: (n) => `Olá ${n},\n\nobrigado pelo seu interesse no Compounding. Com este link acede ao Compounder Portal — economia, retorno, parâmetros técnicos, ligações, plantas e modelo de distribuição.\n\nO link é pessoal, não o partilhe.`,
    inviteLink: 'Abrir o Compounder Portal',
    loginSubject: 'Iniciar sessão no Compounder Portal',
    loginPreheader: 'Link para iniciar sessão no Compounder Portal (válido 24 horas).',
    loginBody: (n) => `Olá${n ? ' ' + n : ''},\n\ncom este link inicia sessão no Compounder Portal. O link é válido 24 horas e é pessoal — não o partilhe.\n\nSe não solicitou este início de sessão, pode ignorar este e-mail.`,
    loginLink: 'Iniciar sessão no Portal',
  },
  nl: {
    inviteSubject: 'Toegang tot het Compounder Portal',
    invitePreheader: 'Uw persoonlijke toegang tot de economie, het rendement en de parameters van de Compounder.',
    inviteBody: (n) => `Hallo ${n},\n\nbedankt voor uw interesse in Compounding. Met deze link krijgt u toegang tot het Compounder Portal — economie, rendement, technische parameters, aansluitingen, plattegronden en het distributiemodel.\n\nDeze link is persoonlijk, deel hem niet.`,
    inviteLink: 'Compounder Portal openen',
    loginSubject: 'Inloggen op het Compounder Portal',
    loginPreheader: 'Link om in te loggen op het Compounder Portal (24 uur geldig).',
    loginBody: (n) => `Hallo${n ? ' ' + n : ''},\n\nmet deze link logt u in op het Compounder Portal. De link is 24 uur geldig en persoonlijk — deel hem niet.\n\nAls u deze login niet hebt aangevraagd, kunt u deze e-mail negeren.`,
    loginLink: 'Inloggen op het Portal',
  },
  pl: {
    inviteSubject: 'Dostęp do Compounder Portal',
    invitePreheader: 'Twój osobisty dostęp do ekonomii, zwrotu i parametrów Compoundera.',
    inviteBody: (n) => `Dzień dobry ${n},\n\ndziękujemy za zainteresowanie Compoundingiem. Ten link daje dostęp do Compounder Portal — ekonomia, zwrot, parametry techniczne, przyłącza, rzuty i model dystrybucji.\n\nLink jest osobisty, prosimy go nie udostępniać.`,
    inviteLink: 'Otwórz Compounder Portal',
    loginSubject: 'Logowanie do Compounder Portal',
    loginPreheader: 'Link do logowania do Compounder Portal (ważny 24 godziny).',
    loginBody: (n) => `Dzień dobry${n ? ' ' + n : ''},\n\nten link umożliwia zalogowanie do Compounder Portal. Link jest ważny 24 godziny i jest osobisty — prosimy go nie udostępniać.\n\nJeśli nie prosiłeś o to logowanie, możesz zignorować tę wiadomość.`,
    loginLink: 'Zaloguj się do Portalu',
  },
  bg: {
    inviteSubject: 'Достъп до Compounder Portal',
    invitePreheader: 'Вашият личен достъп до икономиката, възвръщаемостта и параметрите на Compounder.',
    inviteBody: (n) => `Здравейте, ${n},\n\nблагодарим за интереса към Compounding. С този линк получавате достъп до Compounder Portal — икономика, възвръщаемост, технически параметри, връзки, планове и модел на дистрибуция.\n\nЛинкът е личен, моля не го споделяйте.`,
    inviteLink: 'Отвори Compounder Portal',
    loginSubject: 'Вход в Compounder Portal',
    loginPreheader: 'Линк за вход в Compounder Portal (валиден 24 часа).',
    loginBody: (n) => `Здравейте${n ? ', ' + n : ''},\n\nс този линк ще влезете в Compounder Portal. Линкът е валиден 24 часа и е личен — моля не го споделяйте.\n\nАко не сте поискали този вход, можете да игнорирате този имейл.`,
    loginLink: 'Вход в Portal',
  },
  da: {
    inviteSubject: 'Adgang til Compounder Portal',
    invitePreheader: 'Din personlige adgang til økonomi, afkast og parametre for Compounderen.',
    inviteBody: (n) => `Hej ${n},\n\ntak for din interesse i Compounding. Med dette link får du adgang til Compounder Portal — økonomi, afkast, tekniske parametre, tilslutninger, plantegninger og distributionsmodellen.\n\nLinket er personligt, del det venligst ikke.`,
    inviteLink: 'Åbn Compounder Portal',
    loginSubject: 'Log ind på Compounder Portal',
    loginPreheader: 'Link til at logge ind på Compounder Portal (gyldigt i 24 timer).',
    loginBody: (n) => `Hej${n ? ' ' + n : ''},\n\nmed dette link logger du ind på Compounder Portal. Linket er gyldigt i 24 timer og er personligt — del det venligst ikke.\n\nHvis du ikke har anmodet om dette login, kan du ignorere denne e-mail.`,
    loginLink: 'Log ind på Portal',
  },
  el: {
    inviteSubject: 'Πρόσβαση στο Compounder Portal',
    invitePreheader: 'Η προσωπική σας πρόσβαση στα οικονομικά, την απόδοση και τις παραμέτρους του Compounder.',
    inviteBody: (n) => `Γεια σας ${n},\n\nσας ευχαριστούμε για το ενδιαφέρον σας για το Compounding. Με αυτόν τον σύνδεσμο αποκτάτε πρόσβαση στο Compounder Portal — οικονομικά, απόδοση, τεχνικές παράμετροι, συνδέσεις, κατόψεις και μοντέλο διανομής.\n\nΟ σύνδεσμος είναι προσωπικός, μην τον κοινοποιείτε.`,
    inviteLink: 'Άνοιγμα του Compounder Portal',
    loginSubject: 'Σύνδεση στο Compounder Portal',
    loginPreheader: 'Σύνδεσμος για σύνδεση στο Compounder Portal (ισχύει για 24 ώρες).',
    loginBody: (n) => `Γεια σας${n ? ' ' + n : ''},\n\nμε αυτόν τον σύνδεσμο συνδέεστε στο Compounder Portal. Ο σύνδεσμος ισχύει για 24 ώρες και είναι προσωπικός — μην τον κοινοποιείτε.\n\nΕάν δεν ζητήσατε αυτήν τη σύνδεση, αγνοήστε αυτό το email.`,
    loginLink: 'Σύνδεση στο Portal',
  },
  et: {
    inviteSubject: 'Juurdepääs Compounder Portalile',
    invitePreheader: 'Teie isiklik juurdepääs Compounderi majandusele, tootlusele ja parameetritele.',
    inviteBody: (n) => `Tere ${n},\n\ntäname huvi eest Compoundingu vastu. See link annab teile juurdepääsu Compounder Portalile — majandus, tootlus, tehnilised parameetrid, ühendused, plaanid ja turustusmudel.\n\nLink on isiklik, palun ärge seda jagage.`,
    inviteLink: 'Ava Compounder Portal',
    loginSubject: 'Logi sisse Compounder Portalisse',
    loginPreheader: 'Link Compounder Portalisse sisselogimiseks (kehtib 24 tundi).',
    loginBody: (n) => `Tere${n ? ' ' + n : ''},\n\nselle lingiga logite sisse Compounder Portalisse. Link kehtib 24 tundi ja on isiklik — palun ärge seda jagage.\n\nKui te seda sisselogimist ei taotlenud, võite selle e-kirja eirata.`,
    loginLink: 'Logi Portalisse',
  },
  fi: {
    inviteSubject: 'Pääsy Compounder Portaliin',
    invitePreheader: 'Henkilökohtainen pääsysi Compounderin talouteen, tuottoon ja parametreihin.',
    inviteBody: (n) => `Hei ${n},\n\nkiitos kiinnostuksestasi Compoundingia kohtaan. Tällä linkillä pääset Compounder Portaliin — talous, tuotto, tekniset parametrit, liitännät, pohjapiirrokset ja jakelumalli.\n\nLinkki on henkilökohtainen, älä jaa sitä.`,
    inviteLink: 'Avaa Compounder Portal',
    loginSubject: 'Kirjaudu Compounder Portaliin',
    loginPreheader: 'Linkki kirjautumiseen Compounder Portaliin (voimassa 24 tuntia).',
    loginBody: (n) => `Hei${n ? ' ' + n : ''},\n\ntällä linkillä kirjaudut Compounder Portaliin. Linkki on voimassa 24 tuntia ja se on henkilökohtainen — älä jaa sitä.\n\nJos et pyytänyt tätä kirjautumista, voit jättää tämän viestin huomiotta.`,
    loginLink: 'Kirjaudu Portaliin',
  },
  ga: {
    inviteSubject: 'Rochtain ar an Compounder Portal',
    invitePreheader: 'Do rochtain phearsanta ar gheilleagar, toradh agus paraiméadair an Compounder.',
    inviteBody: (n) => `Dia duit ${n},\n\ngo raibh maith agat as do shuim i gCompounding. Tugann an nasc seo rochtain duit ar an Compounder Portal — geilleagar, toradh, paraiméadair theicniúla, naisc, pleananna urláir agus an múnla dáilte.\n\nIs nasc pearsanta é, ná roinn é le do thoil.`,
    inviteLink: 'Oscail an Compounder Portal',
    loginSubject: 'Logáil isteach sa Compounder Portal',
    loginPreheader: 'Nasc chun logáil isteach sa Compounder Portal (bailí ar feadh 24 uair).',
    loginBody: (n) => `Dia duit${n ? ' ' + n : ''},\n\nlogáil isteach sa Compounder Portal leis an nasc seo. Tá an nasc bailí ar feadh 24 uair agus tá sé pearsanta — ná roinn é.\n\nMura ndearna tú an logáil isteach seo a iarraidh, déan neamhaird den ríomhphost seo.`,
    loginLink: 'Logáil isteach sa Portal',
  },
  hr: {
    inviteSubject: 'Pristup Compounder Portalu',
    invitePreheader: 'Vaš osobni pristup ekonomiji, povratu i parametrima Compoundera.',
    inviteBody: (n) => `Dobar dan, ${n},\n\nhvala na zanimanju za Compounding. Ovom poveznicom pristupate Compounder Portalu — ekonomija, povrat, tehnički parametri, priključci, tlocrti i distribucijski model.\n\nPoveznica je osobna, nemojte je dijeliti.`,
    inviteLink: 'Otvori Compounder Portal',
    loginSubject: 'Prijava u Compounder Portal',
    loginPreheader: 'Poveznica za prijavu u Compounder Portal (vrijedi 24 sata).',
    loginBody: (n) => `Dobar dan${n ? ', ' + n : ''},\n\novom poveznicom prijavljujete se u Compounder Portal. Poveznica vrijedi 24 sata i osobna je — nemojte je dijeliti.\n\nAko niste zatražili ovu prijavu, slobodno zanemarite ovu poruku.`,
    loginLink: 'Prijava u Portal',
  },
  hu: {
    inviteSubject: 'Belépés a Compounder Portálra',
    invitePreheader: 'Az Ön személyes hozzáférése a Compounder gazdaságosságához, megtérüléséhez és paramétereihez.',
    inviteBody: (n) => `Jó napot, ${n},\n\nköszönjük érdeklődését a Compounding iránt. Ezzel a linkkel beléphet a Compounder Portálra — gazdaságosság, megtérülés, műszaki paraméterek, csatlakozások, alaprajzok és értékesítési modell.\n\nA link személyes, kérjük, ne ossza meg.`,
    inviteLink: 'Compounder Portál megnyitása',
    loginSubject: 'Bejelentkezés a Compounder Portálra',
    loginPreheader: 'Link a Compounder Portálra való bejelentkezéshez (24 óráig érvényes).',
    loginBody: (n) => `Jó napot${n ? ', ' + n : ''},\n\nezzel a linkkel beléphet a Compounder Portálra. A link 24 óráig érvényes és személyes — kérjük, ne ossza meg.\n\nHa nem Ön kérte ezt a bejelentkezést, nyugodtan hagyja figyelmen kívül ezt az e-mailt.`,
    loginLink: 'Bejelentkezés a Portálra',
  },
  lt: {
    inviteSubject: 'Prieiga prie Compounder Portal',
    invitePreheader: 'Jūsų asmeninė prieiga prie Compounder ekonomikos, grąžos ir parametrų.',
    inviteBody: (n) => `Sveiki, ${n},\n\ndėkojame, kad domitės Compounding. Ši nuoroda suteikia prieigą prie Compounder Portal — ekonomika, grąža, techniniai parametrai, jungtys, planai ir platinimo modelis.\n\nNuoroda yra asmeninė, prašome ja nesidalyti.`,
    inviteLink: 'Atidaryti Compounder Portal',
    loginSubject: 'Prisijungimas prie Compounder Portal',
    loginPreheader: 'Nuoroda prisijungti prie Compounder Portal (galioja 24 valandas).',
    loginBody: (n) => `Sveiki${n ? ', ' + n : ''},\n\nšia nuoroda prisijungsite prie Compounder Portal. Nuoroda galioja 24 valandas ir yra asmeninė — prašome ja nesidalyti.\n\nJei šio prisijungimo neprašėte, galite šį laišką ignoruoti.`,
    loginLink: 'Prisijungti prie Portal',
  },
  lv: {
    inviteSubject: 'Piekļuve Compounder Portal',
    invitePreheader: 'Jūsu personīgā piekļuve Compounder ekonomikai, atdevei un parametriem.',
    inviteBody: (n) => `Labdien, ${n},\n\npaldies par interesi par Compounding. Šī saite sniedz piekļuvi Compounder Portal — ekonomika, atdeve, tehniskie parametri, pieslēgumi, plāni un izplatīšanas modelis.\n\nSaite ir personīga, lūdzu, nedalieties ar to.`,
    inviteLink: 'Atvērt Compounder Portal',
    loginSubject: 'Pieslēgšanās Compounder Portal',
    loginPreheader: 'Saite, lai pieslēgtos Compounder Portal (derīga 24 stundas).',
    loginBody: (n) => `Labdien${n ? ', ' + n : ''},\n\nar šo saiti jūs pieslēgsieties Compounder Portal. Saite ir derīga 24 stundas un ir personīga — lūdzu, nedalieties ar to.\n\nJa neesat pieprasījis šo pieslēgšanos, varat šo e-pastu ignorēt.`,
    loginLink: 'Pieslēgties Portal',
  },
  mt: {
    inviteSubject: 'Aċċess għall-Compounder Portal',
    invitePreheader: "L-aċċess personali tiegħek għall-ekonomija, ir-redditu u l-parametri tal-Compounder.",
    inviteBody: (n) => `Bonġu ${n},\n\ngrazzi tal-interess tiegħek fil-Compounding. Din il-link tagħtik aċċess għall-Compounder Portal — ekonomija, redditu, parametri tekniċi, konnessjonijiet, pjanti u l-mudell ta' distribuzzjoni.\n\nIl-link hija personali, jekk jogħġbok tikkondividihiex.`,
    inviteLink: 'Iftaħ il-Compounder Portal',
    loginSubject: 'Idħol fil-Compounder Portal',
    loginPreheader: 'Link biex tidħol fil-Compounder Portal (valida għal 24 siegħa).',
    loginBody: (n) => `Bonġu${n ? ' ' + n : ''},\n\nb'din il-link tidħol fil-Compounder Portal. Il-link hija valida għal 24 siegħa u hija personali — jekk jogħġbok tikkondividihiex.\n\nJekk ma tlabtx dan id-dħul, tista' tinjora din l-email.`,
    loginLink: 'Idħol fil-Portal',
  },
  ro: {
    inviteSubject: 'Acces la Compounder Portal',
    invitePreheader: 'Accesul dumneavoastră personal la economia, randamentul și parametrii Compounderului.',
    inviteBody: (n) => `Bună ziua, ${n},\n\nvă mulțumim pentru interesul față de Compounding. Acest link vă oferă acces la Compounder Portal — economie, randament, parametri tehnici, racorduri, planuri și modelul de distribuție.\n\nLinkul este personal, vă rugăm să nu îl distribuiți.`,
    inviteLink: 'Deschide Compounder Portal',
    loginSubject: 'Autentificare în Compounder Portal',
    loginPreheader: 'Link pentru autentificare în Compounder Portal (valabil 24 de ore).',
    loginBody: (n) => `Bună ziua${n ? ', ' + n : ''},\n\ncu acest link vă autentificați în Compounder Portal. Linkul este valabil 24 de ore și este personal — vă rugăm să nu îl distribuiți.\n\nDacă nu ați solicitat această autentificare, puteți ignora acest e-mail.`,
    loginLink: 'Autentificare în Portal',
  },
  sl: {
    inviteSubject: 'Dostop do Compounder Portala',
    invitePreheader: 'Vaš osebni dostop do ekonomike, donosa in parametrov Compounderja.',
    inviteBody: (n) => `Pozdravljeni, ${n},\n\nhvala za zanimanje za Compounding. S to povezavo dostopate do Compounder Portala — ekonomika, donos, tehnični parametri, priključki, tlorisi in distribucijski model.\n\nPovezava je osebna, prosimo, ne delite je.`,
    inviteLink: 'Odpri Compounder Portal',
    loginSubject: 'Prijava v Compounder Portal',
    loginPreheader: 'Povezava za prijavo v Compounder Portal (velja 24 ur).',
    loginBody: (n) => `Pozdravljeni${n ? ', ' + n : ''},\n\ns to povezavo se prijavite v Compounder Portal. Povezava velja 24 ur in je osebna — prosimo, ne delite je.\n\nČe te prijave niste zahtevali, lahko to sporočilo prezrete.`,
    loginLink: 'Prijava v Portal',
  },
  sv: {
    inviteSubject: 'Åtkomst till Compounder Portal',
    invitePreheader: 'Din personliga åtkomst till Compounderns ekonomi, avkastning och parametrar.',
    inviteBody: (n) => `Hej ${n},\n\ntack för ditt intresse för Compounding. Den här länken ger dig åtkomst till Compounder Portal — ekonomi, avkastning, tekniska parametrar, anslutningar, planritningar och distributionsmodellen.\n\nLänken är personlig, dela den inte.`,
    inviteLink: 'Öppna Compounder Portal',
    loginSubject: 'Logga in på Compounder Portal',
    loginPreheader: 'Länk för att logga in på Compounder Portal (giltig i 24 timmar).',
    loginBody: (n) => `Hej${n ? ' ' + n : ''},\n\nmed den här länken loggar du in på Compounder Portal. Länken är giltig i 24 timmar och är personlig — dela den inte.\n\nOm du inte begärde denna inloggning kan du ignorera detta e-postmeddelande.`,
    loginLink: 'Logga in på Portal',
  },
};

// Normalizuje jazykový kód (např. "de-DE" → "de") a vrátí podporovaný kód
// nebo "en" jako fallback.
function pickLang(lang) {
  const code = String(lang || '').toLowerCase().split(/[-_]/)[0];
  return T[code] ? code : 'en';
}

function inviteEmail(name, lang) {
  const t = T[pickLang(lang)];
  return {
    subject: t.inviteSubject,
    preheader: t.invitePreheader,
    body: t.inviteBody(name || ''),
    linkLabel: t.inviteLink,
  };
}

function loginEmail(name, lang) {
  const t = T[pickLang(lang)];
  return {
    subject: t.loginSubject,
    preheader: t.loginPreheader,
    body: t.loginBody(name || ''),
    linkLabel: t.loginLink,
  };
}

module.exports = { inviteEmail, loginEmail, pickLang };
